trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

- task: PackageAzureDevOpsExtension@4
  displayName: 'Package Extension: $(Build.SourcesDirectory)'
  name: 'packageStep'
  inputs:
    rootFolder: '$(Build.SourcesDirectory)'
    outputPath: '$(Build.ArtifactStagingDirectory)\vsts-developer-tools-build-tasks.vsix'
    updateTasksVersion: false
    extensionVisibility: 'public'

- task: PublishAzureDevOpsExtension@4
  displayName: "Publish Extension to Visual Studio Marketplace"
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: 'marketplaceServiceConnection'
    fileType: 'vsix'
    vsixFile: '*.vsix'
    extensionVisibility: 'public'

