trigger:
- main

pool:
  vmImage: ubuntu-latest

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'
steps:

- script: dotnet build ShiftEntity.VSIX.Template --configuration release
  displayName: 'dotnet build '

- task: PublishVisualStudioExtension@4
  displayName: "Publish Extension to Visual Studio Marketplace"
  inputs:
    connectedServiceName: 'marketplaceServiceConnection'
    vsixFile: '$(Build.ArtifactStagingDirectory)/bin/Release/ShiftEntity.VSIX.Template.vsix'
    manifestFile: 'manifest.json'
    publisherId: 'shiftsoftware'

