trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: dotnet build ShiftEntity.VSIX.Template --configuration release --output $(Build.ArtifactStagingDirectory)/bin/Release
  displayName: 'dotnet build '
  continueOnError: true

- task: PublishVisualStudioExtension@4
  displayName: "Publish Extension to Visual Studio Marketplace"
  inputs:
    connectedServiceName: 'marketplaceServiceConnection'
    vsixFile: '$(Build.ArtifactStagingDirectory)/bin/Release/ShiftEntity.VSIX.Template.vsix'
    manifestFile: '$(Build.ArtifactStagingDirectory)/bin/Release/manifest.json'
    publisherId: 'shiftsoftware'

