trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
# - task: NuGetCommand@2
#   inputs:
#     command: 'restore'
#     restoreSolution: '**/ShiftEntity.VSIX.Template.csproj'
#     feedsToUse: 'select'

- task: DownloadGitHubNugetPackage@1
  inputs:
    packageName: 'Microsoft.VSSDK.BuildTools'
    version: '17.7.2192'
- task: DownloadGitHubNugetPackage@1
  inputs:
    packageName: 'Microsoft.VisualStudio.SDK'
    version: '17.0.32112.339'

- script: dotnet build ShiftEntity.VSIX.Template --configuration release
  displayName: 'dotnet build'

- task: PublishAzureDevOpsExtension@4
  displayName: "Publish Extension to Visual Studio Marketplace"
  inputs:
    connectTo: 'VsTeam'
    connectedServiceName: 'marketplaceServiceConnection'
    fileType: 'vsix'
    vsixFile: '*.vsix'
    extensionVisibility: 'public'

