trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:

 - script: dotnet build ShiftEntity.Web --configuration release
   displayName: 'dotnet build'

 - script: dotnet pack ShiftEntity.Web --configuration release --output $(Build.ArtifactStagingDirectory)
   displayName: 'dotnet pack'

 - task: NuGetCommand@2
   inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org'