#!/bin/sh

# Temporarily modify the project file to remove shift framework references. Linux
sed -i '/<ProjectReference Include="..\\..\\TypeAuth\\TypeAuth.AspNetCore\\TypeAuth.AspNetCore" \\/d' ShiftEntity.Web/ShiftEntity.Web.csproj

# Temporarily modify the project file to remove shift framework references. Windows
sed -i "/<ProjectReference Include=\"..\\\\..\\\\TypeAuth\\\\TypeAuth.AspNetCore\\\\TypeAuth.AspNetCore.csproj\" \\/>/d" ShiftEntity.Web/ShiftEntity.Web.csproj


# Stage the modified file
git add ShiftEntity.Web/ShiftEntity.Web.csproj

