using Microsoft.Extensions.Caching.Memory;
using Microsoft.Extensions.Logging;
using Microsoft.Extensions.Options;
using Newtonsoft.Json.Linq;
using System;
using System.Collections.Generic;
using System.Net;
using System.Net.Http;
using System.Net.Http.Json;
using System.Text;
using System.Text.Json;
using System.Text.Json.Serialization;
using System.Threading.Tasks;

namespace ShiftSoftware.ShiftEntity.Functions.Services.Attestation
{
    public class HMSUserDetectService
    {
        private const string HMSCacheKey = "HMS_ACCESS_TOKEN";

        private readonly ILogger logger;
        private readonly HttpClient httpClient;
        private readonly HMSUserDetectOptions options;
        private readonly IMemoryCache memoryCache;
        public HMSUserDetectService(ILogger<HMSUserDetectService> logger,
            IHttpClientFactory httpClientFactory,
            IOptions<HMSUserDetectOptions> options,
            IMemoryCache memoryCache)
        {
            this.logger = logger;
            httpClient = httpClientFactory.CreateClient(nameof(HMSUserDetectService));
            this.options = options.Value;
            this.memoryCache = memoryCache;
        }

        /// <summary>
        /// Verifies a Huawei Mobile Services (HMS) UserDetect token by performing 
        /// a server-to-server validation call to the Huawei Risk Management Service (RMS).
        /// </summary>
        /// <remarks>
        /// This method performs the following steps:
        /// <list type="bullet">
        /// <item>Retrieves a cached or fresh OAuth 2.0 Access Token from Huawei's Identity provider.</item>
        /// <item>Sends the client's <paramref name="responseToken"/> and the Access Token to the RMS verify endpoint.</item>
        /// <item>Validates the 'success' boolean and logs the structured risk result for audit purposes.</item>
        /// </list>
        /// </remarks>
        /// <param name="responseToken">The integrity response string generated by the HMS Core SDK on the mobile device.</param>
        /// <returns>
        /// <see langword="true"/> if the HMS cloud service confirms the token is valid and the device/user 
        /// is deemed trustworthy; otherwise, <see langword="false"/>.
        /// </returns>
        /// <exception cref="HttpRequestException">Thrown if the network call to Huawei's servers fails.</exception>
        public async ValueTask<bool> VerifyTokenAsync(string responseToken)
        {
            var accessToken = await memoryCache.GetOrCreateAsync(HMSCacheKey, async entry =>
            {
                var oauthResponse = await GetHMSAccessTokenAsync();

                var expirationSeconds = oauthResponse.ExpiresIn.HasValue ? oauthResponse.ExpiresIn.Value - 200 : 3400; // Subtract 200 seconds to be safe
                entry.AbsoluteExpirationRelativeToNow = TimeSpan.FromSeconds(expirationSeconds);
                return oauthResponse.AccessToken;
            });

            if (string.IsNullOrWhiteSpace(accessToken))
            {
                logger.LogError("Failed to retrieve HMS Access Token from cache and API.");
                return false;
            }

            try
            {
                var response = await httpClient.PostAsJsonAsync(
                    $"https://hirms.cloud.huawei.com/rms/v1/userRisks/verify?appId={options.HMSAppId}",
                    new HMSUserDetectRequestBody
                    {
                        AccessToken = accessToken,
                        Response = responseToken
                    }
                );

                if (response.StatusCode == HttpStatusCode.OK)
                {
                    var userDetectResult = await response.Content.ReadFromJsonAsync<HMSUserDetectResponseBody>();

                    logger.LogInformation("HMS User Detect Result:\n{@Result}", JsonSerializer.Serialize(userDetectResult));
                    if (userDetectResult is not null && userDetectResult.Success)
                    {
                        return true;
                    }
                    return false;
                }
                else
                {
                    logger.LogError("Failed to verify HMS User. Status Code: {StatusCode}\nResponse: {Response}",
                        response.StatusCode,
                        await response.Content.ReadAsStringAsync());
                }
            }
            catch (Exception ex)
            {
                logger.LogError(ex, "HMS User Detection Failed");
                return false;
            }

            return false;
        }

        /// <summary>
        /// Obtains an OAuth 2.0 Access Token using the Client Credentials grant type. 
        /// Results are cached locally via <see cref="IMemoryCache"/> for 55 minutes to 
        /// optimize performance and respect Huawei API rate limits.
        /// </summary>
        /// <returns>A valid Bearer token for Huawei cloud service authentication, or <see langword="null"/> if authentication fails.</returns>
        private async Task<HMSOAuthResponse> GetHMSAccessTokenAsync()
        {
            var authPayload = new List<KeyValuePair<string, string>>()
            {
                KeyValuePair.Create("grant_type", "client_credentials"),
                KeyValuePair.Create("client_id", options.HMSClientId),
                KeyValuePair.Create("client_secret", options.HMSClientSecret),
            };
            var encodedPaylod = new FormUrlEncodedContent(authPayload);
            encodedPaylod.Headers.ContentType = new("application/x-www-form-urlencoded");

            var authResponse = await httpClient.PostAsync(
                "https://oauth-login.cloud.huawei.com/oauth2/v3/token",
               encodedPaylod
            );

            if (authResponse.StatusCode == HttpStatusCode.OK)
            {
                var oauthResponse = await authResponse.Content.ReadFromJsonAsync<HMSOAuthResponse>();
                return oauthResponse!;
            }
            else
            {
                logger.LogError("Failed to get HMS Access Token. Status Code: {StatusCode}\nResponse: {Response}",
                    authResponse.StatusCode,
                    await authResponse.Content.ReadAsStringAsync());
                throw new Exception("Failed to get HMS Access Token");
            }
        }
    }

    internal class HMSUserDetectRequestBody
    {
        [JsonPropertyName("accessToken")]
        public string AccessToken { get; set; } = default!;
        [JsonPropertyName("response")]
        public string Response { get; set; } = default!;
    }

    internal class HMSUserDetectResponseBody
    {
        [JsonPropertyName("success")]
        public bool Success { get; set; } = default!;
        [JsonPropertyName("error-codes")]
        public string ErrorCodes { get; set; } = default!;
        [JsonPropertyName("challenge_ts")]
        public string? ChallengeTS { get; set; }
        [JsonPropertyName("apk_package_name")]
        public string? APKPackageName { get; set; }
    }
    internal class HMSOAuthResponse
    {
        [JsonPropertyName("access_token")]
        public required string AccessToken { get; set; }
        [JsonPropertyName("token_type")]
        public required string TokenType { get; set; }
        [JsonPropertyName("expires_in")]
        public int? ExpiresIn { get; set; }
    }
    public class HMSUserDetectOptions
    {
        public string HMSClientId { get; set; } = default!;
        public string HMSClientSecret { get; set; } = default!;
        public string HMSAppId { get; set; } = default!;
    }
}
